import 'package:cloud_firestore/cloud_firestore.dart';

/// One attraction entry inside a saved trip plan's `attractions` array -
/// see [SavedTripPlan]'s own doc comment for where this data comes
/// from. Deliberately its own small class rather than importing the AI
/// Trip Planner module's own AttractionModel (attraction.dart) - the
/// transportation module only reads the handful of raw fields it
/// actually needs (name/address/area for geocoding; day for grouping
/// into a daily itinerary; openingTime/closingTime/recommendedDuration
/// for working out a real per-attraction visit schedule - see
/// [recommendedVisitMinutes]/[openingDateTime]/[closingDateTime]), not
/// that module's full attraction shape, so a field it adds or renames
/// later can't silently break this one.
class SavedTripPlanAttraction {
  const SavedTripPlanAttraction({
    required this.name,
    required this.address,
    required this.area,
    required this.day,
    required this.openingTime,
    required this.closingTime,
    required this.recommendedDuration,
  });

  final String name;
  final String address;
  final String area;

  /// 1-indexed day within the trip (day 1 = the plan's own startDate) -
  /// see GeneratedTripPage._getAttractionDay, the only place that
  /// writes it.
  final int day;

  /// Raw opening/closing time strings exactly as saved (e.g. "09:00",
  /// "9:00 AM" - see AttractionModel.openingTime/closingTime) and the
  /// free-text visit-duration option picked in AttractionFormPage (e.g.
  /// "1 - 2 hours", "Half Day") - see [recommendedVisitMinutes] and
  /// [openingDateTime]/[closingDateTime] below for how these get turned
  /// into real DateTimes/minutes. Kept as raw strings here (not parsed
  /// at construction) so a malformed value never breaks loading the
  /// whole plan - parsing happens lazily, with a safe fallback, only
  /// when a caller actually asks for a DateTime/minute count.
  final String openingTime;
  final String closingTime;
  final String recommendedDuration;

  /// How long a visit here is expected to take, in minutes - mirrors
  /// AiTripPlannerController._recommendedVisitMinutes exactly (same
  /// parsing rules, same 30-360 clamp, same 90-minute fallback) so a
  /// plan generated by that module and a route planned here from the
  /// same saved data land on the same numbers. Deliberately its own
  /// copy of that small algorithm rather than an import - see this
  /// file's own doc comment on why the transportation module never
  /// imports the AI Trip Planner module's classes.
  int get recommendedVisitMinutes {
    final value = recommendedDuration.trim().toLowerCase();
    if (value.isEmpty) return 90;

    final match = RegExp(r'[0-9]+(?:\.[0-9]+)?').firstMatch(value);
    if (match == null) return 90;

    final number = double.tryParse(match.group(0) ?? '');
    if (number == null) return 90;

    if (value.contains('hour') || value.contains('hr')) {
      return (number * 60).round().clamp(30, 360);
    }
    return number.round().clamp(30, 360);
  }

  /// This attraction's real opening time, as a DateTime on [dayDate]
  /// (only that date's year/month/day is used - hour/minute are
  /// ignored). Mirrors AiTripPlannerController._openingDateTime/
  /// _parseTime (same "09:00" / "9:00 AM" parsing, same 9am fallback
  /// when [openingTime] is empty or unparseable).
  DateTime openingDateTime(DateTime dayDate) {
    return _dateAt(dayDate, _parseTimeOfDay(openingTime, 9 * 60));
  }

  /// This attraction's real closing time, as a DateTime on [dayDate] -
  /// see [openingDateTime]. Falls back to 6pm when [closingTime] is
  /// empty or unparseable, mirroring
  /// AiTripPlannerController._closingDateTime.
  DateTime closingDateTime(DateTime dayDate) {
    return _dateAt(dayDate, _parseTimeOfDay(closingTime, 18 * 60));
  }

  static int _parseTimeOfDay(String rawValue, int fallbackMinutes) {
    final value = rawValue.trim().toUpperCase();
    if (value.isEmpty) return fallbackMinutes;

    final match = RegExp(
      r'(\d{1,2})[:.]?(\d{2})?\s*(AM|PM)?',
    ).firstMatch(value);
    if (match == null) return fallbackMinutes;

    int hour = int.tryParse(match.group(1) ?? '') ?? 0;
    final minute = int.tryParse(match.group(2) ?? '') ?? 0;
    final period = match.group(3);

    if (period == 'PM' && hour < 12) hour += 12;
    if (period == 'AM' && hour == 12) hour = 0;

    if (hour > 23 || minute > 59) return fallbackMinutes;
    return hour * 60 + minute;
  }

  /// DateTime.utc, not DateTime(...) - [openingDateTime]/
  /// [closingDateTime]'s result gets compared directly against a live
  /// search result's own departTime/arriveTime in
  /// TransportController.planTransportationForPlan
  /// (`deadline.isBefore(openingAt)`), and those live results are in
  /// the "isUtc but fields are Malaysia wall clock" representation
  /// documented on HereTransitService's instantToMalaysiaWallClock - a
  /// plain DateTime(...) here would put this attraction's opening time
  /// in a different representation (a genuine real instant, only
  /// correct on a device actually set to Malaysia's own timezone),
  /// making that comparison silently wrong on any other device.
  static DateTime _dateAt(DateTime day, int minutesOfDay) {
    return DateTime.utc(
      day.year,
      day.month,
      day.day,
      minutesOfDay ~/ 60,
      minutesOfDay % 60,
    );
  }

  factory SavedTripPlanAttraction.fromMap(Map<String, dynamic> map) {
    return SavedTripPlanAttraction(
      name: (map['name'] as String?)?.trim() ?? '',
      address: (map['address'] as String?)?.trim() ?? '',
      area: (map['area'] as String?)?.trim() ?? '',
      day: (map['day'] as num?)?.toInt() ?? 1,
      openingTime: (map['openingTime'] as String?)?.trim() ?? '',
      closingTime: (map['closingTime'] as String?)?.trim() ?? '',
      recommendedDuration: (map['recommendedDuration'] as String?)?.trim() ?? '',
    );
  }
}

/// A saved trip plan from the AI Trip Planner module's own
/// `saved_trip_plans` Firestore collection (written by
/// GeneratedTripPage._toggleSavePlan) - read here as a set of plain
/// fields rather than by importing that module's own model classes, so
/// the transportation module stays independent of it (see
/// [SavedTripPlanAttraction]'s doc comment for the same reasoning).
/// Used by TripPlansPage (list every one of these) and
/// TransportController.planTransportationForPlan (plan a real route to
/// every attraction in one).
class SavedTripPlan {
  const SavedTripPlan({
    required this.id,
    required this.selectedState,
    required this.startDate,
    required this.endDate,
    required this.dateSummary,
    required this.totalDays,
    required this.totalAttractions,
    required this.travelStyle,
    required this.attractions,
  });

  final String id;
  final String? selectedState;
  final DateTime startDate;
  final DateTime endDate;

  /// Already a friendly "DD/MM/YYYY - DD/MM/YYYY" string - see
  /// TripPlanPreferences.dateSummary (trip_plan.dart), written verbatim
  /// into the saved document, so this doesn't need to re-derive its own
  /// date formatting.
  final String dateSummary;
  final int totalDays;
  final int totalAttractions;
  final String? travelStyle;
  final List<SavedTripPlanAttraction> attractions;

  /// Attractions for one specific day (1-indexed), in the order they
  /// were saved.
  List<SavedTripPlanAttraction> attractionsForDay(int day) {
    return attractions.where((attraction) => attraction.day == day).toList();
  }

  factory SavedTripPlan.fromFirestore(String id, Map<String, dynamic> data) {
    final startTimestamp = data['startDate'];
    final endTimestamp = data['endDate'];
    final now = DateTime.now();
    final rawAttractions = data['attractions'];

    return SavedTripPlan(
      id: id,
      selectedState: data['selectedState'] as String?,
      startDate: startTimestamp is Timestamp ? startTimestamp.toDate() : now,
      endDate: endTimestamp is Timestamp ? endTimestamp.toDate() : now,
      dateSummary: (data['dateSummary'] as String?) ?? '',
      totalDays: (data['totalDays'] as num?)?.toInt() ?? 0,
      totalAttractions: (data['totalAttractions'] as num?)?.toInt() ?? 0,
      travelStyle: data['travelStyle'] as String?,
      attractions: rawAttractions is List
          ? rawAttractions
                .whereType<Map>()
                .map(
                  (raw) => SavedTripPlanAttraction.fromMap(
                    Map<String, dynamic>.from(raw),
                  ),
                )
                .toList()
          : const [],
    );
  }
}
