// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBstYDZcRmdpLmMfok9GUrNpCT93gX-xA4',
    appId: '1:928647860235:web:b954c139d7fbe58c67770e',
    messagingSenderId: '928647860235',
    projectId: 'ecotravel-5ad49',
    authDomain: 'ecotravel-5ad49.firebaseapp.com',
    storageBucket: 'ecotravel-5ad49.firebasestorage.app',
    measurementId: 'G-5LE47GWVK2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVMEF5aBxakdM4se8BOGslo2NDaQ-3b_4',
    appId: '1:928647860235:android:9f1df2dbb22997f367770e',
    messagingSenderId: '928647860235',
    projectId: 'ecotravel-5ad49',
    storageBucket: 'ecotravel-5ad49.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxbf6pPstfFJpQ9bC-HUs9RYShRjUzk0Y',
    appId: '1:928647860235:ios:a8f517c15af704db67770e',
    messagingSenderId: '928647860235',
    projectId: 'ecotravel-5ad49',
    storageBucket: 'ecotravel-5ad49.firebasestorage.app',
    iosBundleId: 'my.edu.tarumt.collaborativeAsg',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxbf6pPstfFJpQ9bC-HUs9RYShRjUzk0Y',
    appId: '1:928647860235:ios:a8f517c15af704db67770e',
    messagingSenderId: '928647860235',
    projectId: 'ecotravel-5ad49',
    storageBucket: 'ecotravel-5ad49.firebasestorage.app',
    iosBundleId: 'my.edu.tarumt.collaborativeAsg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBstYDZcRmdpLmMfok9GUrNpCT93gX-xA4',
    appId: '1:928647860235:web:600815936210ed5767770e',
    messagingSenderId: '928647860235',
    projectId: 'ecotravel-5ad49',
    authDomain: 'ecotravel-5ad49.firebaseapp.com',
    storageBucket: 'ecotravel-5ad49.firebasestorage.app',
    measurementId: 'G-1VRBC6VYFN',
  );
}
